### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [yalue/cudabrot#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/118353394-925a9b00-b598-11eb-877b-e634ef4bac14.png)

thank you  
best regards to you  
William

**Comment by yalue** [comment]
Hi William,

Thank you for the interest in the project!  Sorry about the error; I suppose my toolchain must have been including the needed file transitively.  I will push an update tomorrow, but in the meantime, if you still want to compile it, you should be able to simply add `#include <errno.h>` to the top of `cudabrot.cu` in order to resolve this error.  Let me know if that helps!

**Comment by yalue** [comment]
Should be fixed as of commit 11dbdbee659b5b05866ede651b8dfbc6c8b3b7a3; let me know if you still have this problem.
